notifications:
    commits:      commits@dubbo.apache.org
    issues:       notifications@dubbo.apache.org
    pullrequests: notifications@dubbo.apache.org
    jira_options: link label link label


github:
  homepage: https://dubbo.apache.org/
  description: "The python Implementation For Apache Dubbo."
  features:
    # Enable wiki for documentation
    wiki: false
    # Enable issue management
    issues: false
    # Enable projects for project management boards
    projects: false
  collaborators:
    - cnzakii
  enabled_merge_buttons:
    # enable squash button:
    squash: true
    # enable merge button:
    merge: false
    # disable rebase button:
    rebase: false
  labels:
    - dubbo
    - python
    - rpc
    - framework
    - http2
    - h2
    - grpc