# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: greeter.proto
# Protobuf Python Version: 5.27.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    0,
    '',
    'greeter.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rgreeter.proto\x12\x1eorg.apache.dubbo.samples.proto\"\x1e\n\x0eGreeterRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1f\n\x0cGreeterReply\x12\x0f\n\x07message\x18\x01 \x01(\t2\xc1\x03\n\x07Greeter\x12h\n\x08sayHello\x12..org.apache.dubbo.samples.proto.GreeterRequest\x1a,.org.apache.dubbo.samples.proto.GreeterReply\x12n\n\x0c\x63lientStream\x12..org.apache.dubbo.samples.proto.GreeterRequest\x1a,.org.apache.dubbo.samples.proto.GreeterReply(\x01\x12n\n\x0cserverStream\x12..org.apache.dubbo.samples.proto.GreeterRequest\x1a,.org.apache.dubbo.samples.proto.GreeterReply0\x01\x12l\n\x08\x62iStream\x12..org.apache.dubbo.samples.proto.GreeterRequest\x1a,.org.apache.dubbo.samples.proto.GreeterReply(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'greeter_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GREETERREQUEST']._serialized_start=49
  _globals['_GREETERREQUEST']._serialized_end=79
  _globals['_GREETERREPLY']._serialized_start=81
  _globals['_GREETERREPLY']._serialized_end=112
  _globals['_GREETER']._serialized_start=115
  _globals['_GREETER']._serialized_end=564
# @@protoc_insertion_point(module_scope)
