# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: unary_unary.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x11unary_unary.proto\x12\x07\x65xample"\x17\n\x07Request\x12\x0c\n\x04name\x18\x01 \x01(\t"\x1b\n\x08Response\x12\x0f\n\x07message\x18\x01 \x01(\t2H\n\x11UnaryUnaryService\x12\x33\n\nUnaryUnary\x12\x10.example.Request\x1a\x11.example.Response"\x00\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "unary_unary_pb2", _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _globals["_REQUEST"]._serialized_start = 30
    _globals["_REQUEST"]._serialized_end = 53
    _globals["_RESPONSE"]._serialized_start = 55
    _globals["_RESPONSE"]._serialized_end = 82
    _globals["_UNARYUNARYSERVICE"]._serialized_start = 84
    _globals["_UNARYUNARYSERVICE"]._serialized_end = 156
# @@protoc_insertion_point(module_scope)
